### ISSUE TITLE
Flat File Support For Multivalued Attributes?

### ISSUE THREAD

**Issue by jkovach82** [Microsoft/MIMPowerShellConnectors#9] opened 2016-08-31 19:53 UTC
I see a comment in the Import script around line 76 ##TODO: Support multivalue?  

My use case is O365 licensing, I have a flat file that contains 2 columns: UPN and Licenses.AccountSkuId; my Licenses.AccountSkuId column is multivalued and formatted "contoso:ENTERPRISEPACK contoso:EMS".

For my use case I had to update the flat file schema to support multivalued attributes:

foreach ($c in $Columns)
{
    if ($c.Name -like "Licenses.AccountSkuId ")
    {
        $SchemaType | Add-xADSyncPSConnectorSchemaAttribute -Name $c.Name -Multivalued:$true -DataType string -SupportedOperation ImportExport
        "Got Here!" | Out-File c:\TEMP\test.txt -Append
        } else {
            $SchemaType | Add-xADSyncPSConnectorSchemaAttribute -Name $c.Name -Multivalued:$false -DataType string -SupportedOperation ImportExport
    }
}

I am reading here that multivalued columns are not supported in MIM: https://technet.microsoft.com/en-us/library/cc708679%28v=ws.10%29.aspx?f=255&MSPPError=-2147217396

What I want to do is to be able to enumerate that AccountSkuId collection so I can manage user license assignment deltas via the MIM portal.

On Exporting:
**Also: the xADSyncPSConnectorModule.psm1 has a syntax error in the New-GenericObject function that must be fixed prior to doing multivalued exports.

After fixing this error I tried to export proxyaddresscollection as a flat file multivalued example and am getting an error in the sync MA.
ERROR: ambiguous-export-flow-to-single-valued-attribute
sync step: Export flow
Data source attribute: ProxyAddresses

**Comment by NileshGhodekar** [comment] 2017-04-28 12:03
Closing this as the issue is better taken up on a TechNet forum.

**Closed as completed by NileshGhodekar** 2017-04-28 12:03 UTC
